- hosts: localhost
  become: true
  tasks:
  - name: Install Packages
    apt:
      pkg:
        - htop
        - google-chrome-stable
        - virtualbox
        - gnome-tweaks
      state: present
